FORMAT: 1A
HOST: https://api-infinitythegame.shrikeh.net/

# infinitythegame

API for the army builder.

## Units Collection [/units]

### List All Units [GET]

+ Response 200 (application/hal+json)

    + Body
    
            {
                "_links": {
                    "self": { "href": "/units" },
                    "curies": [{ "name": "units", "href": "http://example.com/docs/rels/{rel}", "templated": true }],
                    "units:ghulam": {
                        "href": "/units/ghulam",
                        "title: "Ghulam"
                    },
                    "units:hafza": {
                        "href": "/units/hafza",
                        "title: "Hafza"
                    }
                }
            }


## Factions Collection [/factions]

### List All Factions [GET]

+ Response 200 (application/hal+json)

    + Body
    
            {
                "_links": {
                    "self": { "href": "/orders" },
                    "curies": [{ "name": "factions", "href": "http://example.com/docs/rels/{rel}", "templated": true }],
                    "factions:aleph": {
                        "href": "/factions/aleph",
                        "title: "Aleph"
                    },
                    "factions:ariadna": {
                        "href": "/factions/ariadna",
                        "title: "Ariadna"
                    },
                    "factions:haqqislam": {
                        "href": "/factions/haqqislam",
                        "title: "Haqqislam"
                    },
                    "factions:haqqislam": {
                        "href": "/factions/nomads",
                        "title: "Nomads"
                    }
                }
            }
